---
- hosts: localhost
  connection: local

  tasks:
    - name: update apt repositories
      become: true
      apt:
        update_cache: true
        cache_valid_time: 86400
        changed_when: false
