---
- hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: update apt repositories
      apt:
        update_cache: true
        cache_valid_time: 86400
      become: true
      changed_when: false
